#!/bin/bash
cd /homes/gws/nhawkins/repo/deft
mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare6/KBP_2015/corpus/LDC2015E77_TAC_KBP_2015_English_Cold_Start_Evaluation_Source_Corpus/data/mpdf/ -l /projects/WebWare9/nhawkins/crawlFileLists/mpdf/100/mpdfBatch:401 --output_directory /projects/WebWare9/nhawkins/crawlOut/"
mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare6/KBP_2015/corpus/LDC2015E77_TAC_KBP_2015_English_Cold_Start_Evaluation_Source_Corpus/data/mpdf/ -l /projects/WebWare9/nhawkins/crawlFileLists/mpdf/100/mpdfBatch:402 --output_directory /projects/WebWare9/nhawkins/crawlOut/"
