#!/bin/bash

cd /homes/gws/nhawkins/repo/deft

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:1 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:2 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:3 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:4 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:5 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:6 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:7 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:8 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:9 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:10 --output_directory /projects/WebWare9/nhawkins/crawlOut"


mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:11 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:12 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:13 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:14 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:15 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:16 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:17 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:18 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:19 --output_directory /projects/WebWare9/nhawkins/crawlOut"

mvn exec:java -pl washington -Dexec.mainClass="edu.washington.WashingtonNewsSpikeExtractorAppKB" -Dexec.args="--input_directory /projects/WebWare9/nhawkins/crawlCorpus/70k/ -l /projects/WebWare9/nhawkins/crawlFileLists/70k/crawlBatch:20 --output_directory /projects/WebWare9/nhawkins/crawlOut"

